### ISSUE TITLE
LoadVectorStore fails on startup

### ISSUE THREAD

**Issue by gigena-git** [springframeworkguru/spring-ai-rag-expert#1]
Steps:

1. From branch `3-load-vector-documents` do `sudo docker-compose up`.
2. Put the OpenAPI Key in `applicaton.yaml`.
3. Wait till `sudo docker ps` returns all three containers up.
4. Run the application with `mvn spring-boot:run`.

Expected:
Documents should start loading up, as per the video 48 in the Spring AI course (min 4:50). 

Actual:
I see this error message on the project's stacktrace:
```
2024-10-28T18:19:37.243-03:00 ERROR 1850667 --- [spring-ai-rag-expert] [           main] i.m.client.AbstractMilvusGrpcClient      : SearchRequest collectionName:vector_store failed! Exception:{}

io.milvus.exception.ServerException: code: UnexpectedError, reason: code: CollectionNotExists, reason: can't find collection: vector_store
        at io.milvus.client.AbstractMilvusGrpcClient.handleResponse(AbstractMilvusGrpcClient.java:347) ~[milvus-sdk-java-2.3.4.jar:na]
        at io.milvus.client.AbstractMilvusGrpcClient.search(AbstractMilvusGrpcClient.java:1565) ~[milvus-sdk-java-2.3.4.jar:na]
        at io.milvus.client.MilvusServiceClient.lambda$search$31(MilvusServiceClient.java:512) ~[milvus-sdk-java-2.3.4.jar:na]
        at io.milvus.client.MilvusServiceClient.retry(MilvusServiceClient.java:285) ~[milvus-sdk-java-2.3.4.jar:na]
        at io.milvus.client.MilvusServiceClient.search(MilvusServiceClient.java:512) ~[milvus-sdk-java-2.3.4.jar:na]
        at org.springframework.ai.vectorstore.MilvusVectorStore.doSimilaritySearch(MilvusVectorStore.java:372) ~[spring-ai-milvus-store-1.0.0-M3.jar:1.0.0-M3]
        at org.springframework.ai.vectorstore.observation.AbstractObservationVectorStore.lambda$similaritySearch$5(AbstractObservationVectorStore.java:85) ~[spring-ai-core-1.0.0-M3.jar:1.0.0-M3]
        at io.micrometer.observation.Observation.observe(Observation.java:565) ~[micrometer-observation-1.13.6.jar:1.13.6]
        at org.springframework.ai.vectorstore.observation.AbstractObservationVectorStore.similaritySearch(AbstractObservationVectorStore.java:84) ~[spring-ai-core-1.0.0-M3.jar:1.0.0-M3]
        at org.springframework.ai.vectorstore.VectorStore.similaritySearch(VectorStore.java:74) ~[spring-ai-core-1.0.0-M3.jar:1.0.0-M3]
        at guru.springframework.spring_ai_rag_expert.bootstrap.LoadVectorStore.run(LoadVectorStore.java:25) ~[classes/:na]
        at org.springframework.boot.SpringApplication.lambda$callRunner$5(SpringApplication.java:790) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.util.function.ThrowingConsumer$1.acceptWithException(ThrowingConsumer.java:83) ~[spring-core-6.1.14.jar:6.1.14]
        at org.springframework.util.function.ThrowingConsumer.accept(ThrowingConsumer.java:60) ~[spring-core-6.1.14.jar:6.1.14]
        at org.springframework.util.function.ThrowingConsumer$1.accept(ThrowingConsumer.java:88) ~[spring-core-6.1.14.jar:6.1.14]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:789) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.lambda$callRunners$3(SpringApplication.java:774) ~[spring-boot-3.3.5.jar:3.3.5]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[na:na]
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[na:na]
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:774) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:342) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1363) ~[spring-boot-3.3.5.jar:3.3.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1352) ~[spring-boot-3.3.5.jar:3.3.5]
        at guru.springframework.spring_ai_rag_expert.DemoApplication.main(DemoApplication.java:10) ~[classes/:na]
```

Simultaneously on the `milvus-standalone` docker image logs, I see a message like this when the program is launched:
```
milvus-standalone  | [2024/10/28 21:19:37.229 +00:00] [WARN] [proxy/impl.go:2689] ["Search failed to WaitToFinish"] [traceID=6fc0b870a237cf5a0f29bab7199cfc28] [role=proxy] [db=default] [collection=vector_store] [partitions="[]"] [dsl=] [len(PlaceholderGroup)=6156] [OutputFields="[doc_id,content,metadata]"] [search_params="[{\"key\":\"anns_field\",\"value\":\"embedding\"},{\"key\":\"topk\",\"value\":\"4\"},{\"key\":\"metric_type\",\"value\":\"COSINE\"},{\"key\":\"round_decimal\",\"value\":\"-1\"},{\"key\":\"ignore_growing\",\"value\":\"false\"},{\"key\":\"offset\",\"value\":\"0\"},{\"key\":\"params\",\"value\":\"{}\"}]"] [guarantee_timestamp=0] [error="code: UnexpectedError, reason: code: CollectionNotExists, reason: can't find collection: vector_store"]
```

For some reason it cannot find the `vector_store` Vector Store. Also in Minio the bucket is empty.

**Comment by gigena-git** [comment]
I was able to solve this, you just have to add `initialize-schema` to true in `application.yaml`:
```yaml
    vectorstore:
      milvus:
        client:
          host: "localhost"
          port: 19530
          username: "root"
          password: "milvus"
        databaseName: "default"
        collectionName: "vector_store"
        initialize-schema: true
        embeddingDimension: 1536
        indexType: IVF_FLAT
        metricType: COSINE

```
